# Generated by Django 4.0.2 on 2022-02-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='entry_date',
        ),
    ]
